#version 330

uniform sampler2D SceneSampler;

in vec2 texCoord;

layout(std140) uniform SamplerInfo {
    vec2 OutSize;
    vec2 SceneSize;
};

layout(std140) uniform HorusConfig {
    // strength, opening, closing, elapsed seconds
    vec4 Phase;
    vec4 Gold;
    // grade strength, etched-edge strength, outline response, reserved
    vec4 Style;
    vec4 Reserved;
};

out vec4 fragColor;

float luminance(vec3 color) {
    return dot(color, vec3(0.2126, 0.7152, 0.0722));
}

float smoother(float value) {
    value = clamp(value, 0.0, 1.0);
    return value * value * value * (value * (value * 6.0 - 15.0) + 10.0);
}

float gaussian(float value, float width) {
    float normalized = value / max(width, 0.0001);
    return exp(-normalized * normalized);
}

void main() {
    float strength = clamp(Phase.x, 0.0, 1.0);
    float opening = clamp(Phase.y, 0.0, 1.0);
    float closing = clamp(Phase.z, 0.0, 1.0);
    float time = Phase.w;
    vec2 pixel = 1.0 / max(SceneSize, vec2(1.0));

    vec3 scene = texture(SceneSampler, texCoord).rgb;
    vec3 right = texture(SceneSampler, texCoord + vec2(pixel.x, 0.0)).rgb;
    vec3 left = texture(SceneSampler, texCoord - vec2(pixel.x, 0.0)).rgb;
    vec3 up = texture(SceneSampler, texCoord + vec2(0.0, pixel.y)).rgb;
    vec3 down = texture(SceneSampler, texCoord - vec2(0.0, pixel.y)).rgb;

    float aspect = OutSize.x / max(OutSize.y, 1.0);
    vec2 p = (texCoord - 0.5) * vec2(aspect, 1.0);
    float radius = length(p);
    float light = luminance(scene);
    float maximum = max(scene.r, max(scene.g, scene.b));
    float minimum = min(scene.r, min(scene.g, scene.b));
    float saturation = maximum - minimum;

    // Preserve recognizable materials while making the world feel interpreted
    // through dark glass and ancient gold rather than through a generic sepia filter.
    vec3 quietColor = mix(vec3(light), scene, 0.58);
    vec3 warmGrade = quietColor * vec3(1.055, 0.94, 0.76);
    warmGrade = pow(max(warmGrade, vec3(0.0)), vec3(1.07));
    warmGrade *= mix(0.87, 1.04, smoother(light));
    vec3 color = mix(scene, warmGrade, strength * Style.x);

    // Color discontinuities become very fine etched marks. The pale outline
    // generated by Minecraft's Glowing effect reacts much more strongly and
    // therefore reads as a deliberate golden silhouette through cover.
    float colorEdge = length(right - left) + length(up - down);
    float etchedEdge = smoothstep(0.085, 0.36, colorEdge);
    float paleOutline = smoothstep(0.54, 0.94, light)
        * (1.0 - smoothstep(0.10, 0.34, saturation))
        * smoothstep(0.045, 0.24, colorEdge);
    vec3 etchedColor = mix(Gold.rgb * 0.32, Gold.rgb, paleOutline);
    float etchedAmount = etchedEdge
        * (Style.y * 0.12 + paleOutline * Style.z)
        * strength;
    color = mix(color, etchedColor, clamp(etchedAmount, 0.0, 0.78));
    color += Gold.rgb * paleOutline * strength * 0.34;

    // A curved, asymmetric falloff suggests the lids of the Wadjet eye. It
    // suppresses peripheral noise while keeping the centre readable.
    float lidCoordinate = abs(p.y) + p.x * p.x * 0.105;
    float lidShadow = smoothstep(0.30, 0.67, lidCoordinate);
    float leftWeight = 1.0 - smoothstep(-0.72, 1.05, p.x);
    color *= 1.0 - lidShadow * strength * mix(0.31, 0.44, leftWeight);

    // Two almost stationary arcs sit at the edge of perception. Their slow
    // breathing prevents the overlay from looking like a painted HUD graphic.
    float eyeWidth = max(0.0, 1.0 - pow(abs(p.x) / 0.92, 1.7));
    float lidCurve = 0.235 * eyeWidth;
    float lidDistance = abs(abs(p.y) - lidCurve);
    float lidLine = gaussian(lidDistance, 0.0065)
        * (1.0 - smoothstep(0.68, 1.02, abs(p.x)));
    float breath = 0.72 + 0.28 * sin(time * 1.35);
    color += Gold.rgb * lidLine * strength * breath * 0.075;

    // The initial reveal opens like an eye rather than flashing a full-screen
    // overlay. It is mixed by the same smooth envelope, so the first frame is
    // always the untouched scene.
    float openShape = smoother(opening);
    float horizontalProfile = sqrt(max(0.0, 1.0 - pow(p.x / 1.04, 2.0)));
    float apertureHeight = mix(0.010, 1.22, openShape) * horizontalProfile;
    float insideAperture = 1.0 - smoothstep(
        apertureHeight - 0.012,
        apertureHeight + 0.012,
        abs(p.y));
    float openingInfluence = strength
        * (1.0 - smoother((opening - 0.50) / 0.50))
        * 0.92;
    color *= mix(1.0, mix(0.075, 1.0, insideAperture), openingInfluence);
    float apertureRim = gaussian(abs(p.y) - apertureHeight, 0.009)
        * step(abs(p.x), 1.04)
        * openingInfluence;
    color += Gold.rgb * apertureRim * 0.72;

    // A restrained iris resonance makes activation feel alive without adding
    // another competing interface element.
    float irisPulse = 0.5 + 0.5 * sin(time * 1.7);
    float iris = gaussian(radius - mix(0.105, 0.135, irisPulse), 0.008)
        + gaussian(radius - 0.205, 0.006) * 0.35;
    float irisVisibility = strength
        * (1.0 - lidShadow)
        * (0.025 + paleOutline * 0.035);
    color += Gold.rgb * iris * irisVisibility;

    // Closing briefly concentrates the remaining light into the horizontal
    // axis, then hands the untouched scene back without a hard post-chain cut.
    float closingMoment = (1.0 - closing) * closing * 4.0;
    float closingLine = gaussian(p.y, 0.012)
        * (1.0 - smoothstep(0.62, 1.03, abs(p.x)));
    color += Gold.rgb * closingLine * closingMoment * 0.16;

    fragColor = vec4(max(color, vec3(0.0)), 1.0);
}
